### ISSUE TITLE
Mouse click couldn't bind

### ISSUE THREAD

**Issue by Eoksni** [crocket/dired-single#1] opened 2017-05-05 09:38 UTC
`  (define-key dired-mode-map [mouse-1] 'dired-single-buffer-mouse)` as specified in readme didn't work for me, had to use
`(defalias 'dired-mouse-find-file-other-window 'dired-single-buffer-mouse)`
instead.

Emacs 25.2, Win 10

**Comment by crocket** [comment] 2017-05-05 10:29
The problem is that I took over dired-single to put it into melpa-stable.
I don't know how to write emacs lisp.

However, it is a promise that I'll accept any pull request that doesn't look too crazy.

**Comment by jpkotta** [comment] 2018-08-23 16:39
You probably want something more like `(define-key dired-mode-map [remap dired-mouse-find-file-other-window] #'dired-single-buffer-mouse)`.

**Comment by ianpan870102** [comment] 2020-01-20 08:23
@jpkotta  Thanks, this does the trick.
```emacs-lisp
(use-package dired-single
  :preface
  (defun my-dired-init ()
    (define-key dired-mode-map [return] #'dired-single-buffer)
    (define-key dired-mode-map [remap dired-mouse-find-file-other-window] #'dired-single-buffer-mouse)
    (define-key dired-mode-map [remap dired-up-directory] #'dired-single-up-directory))
  :config
  (if (boundp 'dired-mode-map)
      (my-dired-init)
    (add-hook 'dired-load-hook #'my-dired-init)))
```

**Comment by crocket** [comment] 2020-02-26 12:20
I think this is fixed in README's recommended key bindings. If you still think it is not fixed, reopen it.

**Closed by crocket** 2020-02-26 12:20 UTC
